blog_demo/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # /posts/1/comments/4
  resources :posts do
    resources :comments
  end

  # Defines the root path route ("/")
  root "pages#home"
end

blog_demo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

blog_demo/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_rich_text :body
  
end

blog_demo/app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5, maximum: 50 }
    validates :body, presence: true, length: { minimum: 10, maximum: 1000 }
    belongs_to :user
    has_many :comments, dependent: :destroy
end

blog_demo/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

blog_demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blog_demo/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post
    def create
        @comment = @post.comments.create(comment_params)
        @comment.user = current_user

        if @comment.save
            flash[:notice] = 'Comment has been created'
            redirect_to post_path(@post)
        else
            flash[:alert] = 'Comment creation failed'
            redirect_to post_path(@post)
        end
    end

    def destroy
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end

    private

    def set_post
        @post = Post.find(params[:post_id])
    end

    def comment_params
        params.require(:comment).permit(:body)
    end
end

blog_demo/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

blog_demo/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.increment!(:views)
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

blog_demo/app/helpers/application_helper.rb
module ApplicationHelper
end

blog_demo/app/helpers/comments_helper.rb
module CommentsHelper
end

blog_demo/app/helpers/pages_helper.rb
module PagesHelper
end

blog_demo/app/helpers/posts_helper.rb
module PostsHelper
end

blog_demo/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

blog_demo/app/views/comments/_comment.html.erb
<div class="comment-<%= comment.id %> container"
    style="border: 1px solid black; padding: 1em; margen: 1em;">
    <%= comment.user.email %><br />
    <span>Posted <%= time_ago_in_words(comment.created_at) %></span>
    <% if current_user == comment.user %>
    <div class="button-group float-end">
        <%= button_to "Delete", [post, comment], class:"btn btn-danger", method: :delete %>
    </div>
    <% end%>
    <hr />
    <%= comment.body %>
</div>

blog_demo/app/views/comments/_form.html.erb
<%= form_with(model: [post, post.comments.build]) do |f| %>
    <div class="form-control">
        <%= f.rich_text_area :body %>
        <%= f.submit "Reply", class: "btn btn-primary mt-1" %>
    </div>
<% end %>

blog_demo/app/views/layouts/_alerts.html.erb
<% if notice %>
    <p class="notice"><%= notice %></p>
<% elsif alert%>
    <p class="alert"><%= alert %></p>
<%end%>

blog_demo/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Rails Blog", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Blog", posts_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class:"nav-link"%>
        </li>
      </ul>
      <ul class="navbar-nav">
        <%= render 'user/session_manager'%>
      </ul>
    </div>
  </div>
</nav>

blog_demo/app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

blog_demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main>
      <header>
      <%= render 'layouts/navbar'%>
      <%= render 'layouts/alerts'%>
      </header>
      <%= yield %>
    </main>
  </body>
</html>

blog_demo/app/views/pages/about.html.erb
<div class="container">
    <h1>Let's Mingle</h1>
    <p>This is where we get to know one another.</p>
    <%= link_to "Home", root_path%>
</div>

blog_demo/app/views/pages/home.html.erb
<div class="container">
    <h1>My Personal Home Page</h1>
    <p>You can read more about me on my personal blog</p>
    <%= link_to "About Me", about_path, class:'btn btn-primary' %>
    <%= link_to "Blog Posts", posts_path, class:'btn btn-primary'%>

</div>

blog_demo/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

blog_demo/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <h4><%= post.title %></h4>
  <h6><%= post.user.email%></h6>
  <p><%= pluralize(post.views, "view")%></p>
  <p><%= post.body %></p>
</div>

blog_demo/app/views/posts/edit.html.erb
<div class="container">
  <h1>Editing post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Show this post", @post %> |
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>

blog_demo/app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <h1>Posts</h1>

  <div id="posts">
    <% @posts.each do |post| %>
      <%= render post %>
      <p>
        <%= link_to "Show this post", post %>
      </p>
    <% end %>
  </div>
  <div>
  <%= link_to "New post", new_post_path %>
</div>
  <div>
    <%= link_to "Home", root_path%>
  </div>
</div>

blog_demo/app/views/posts/new.html.erb
<div class="container">
  <h1>New post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>

blog_demo/app/views/posts/show.html.erb
<div class="container">
  <%= render @post %>

  <div>
    <%= link_to "Edit this post", edit_post_path(@post) %> |
    <%= link_to "Back to posts", posts_path %>

    <%= button_to "Destroy this post", @post, method: :delete %>
  </div>
</div>

<div class="container">
  <%= render 'comments/form', post: @post %>
  <% @comments.each do |comment|%>
    <%= render 'comments/comment', post: @post, comment: comment%>
  <% end %>
</div>

blog_demo/app/views/user/_session_manager.html.erb
<% if current_user %>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Dropdown
        </a>
        <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
        <li><%= link_to "New Post", new_post_path, class:'dropdown-item'%></li>
        <li><hr class="dropdown-divider"></li>
        <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:'dropdown-item'%></li>
        </ul>
    </li>
<% else %>
    <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%></li>
    <li><%= link_to "Sign In", new_user_session_path, class:'nav-link'%></li>
<% end %>